# Nixpacks Monorepo Configuration
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npm run build",
  "cd frontend && npm run build",
  "mkdir -p /app/backend/dist/public",
  "cp -rv /app/frontend/dist/* /app/backend/dist/public/",
  "ls -la /app/backend/dist/public",
  "test -f /app/backend/dist/public/index.html && echo '✅ Frontend copied!' || echo '❌ Frontend copy FAILED!'"
]

[start]
cmd = "cd /app/backend && chmod +x start.sh && ./start.sh"
