# OpsLab Analytics - Railway Monorepo Config
# This builds both backend and frontend, then serves frontend from backend

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm ci --production=false",
  "cd frontend && npm ci --production=false"
]

[phases.build]
cmds = [
  # Build backend
  "cd backend && npx prisma generate",
  "cd backend && npm run build",

  # Build frontend
  "cd frontend && npm run build",

  # Copy frontend to backend public folder
  "mkdir -p backend/dist/public",
  "cp -r frontend/dist/* backend/dist/public/",

  # Verify copy
  "ls -la backend/dist/public | head -20",
  "test -f backend/dist/public/index.html && echo '✅ SUCCESS: Frontend copied to backend/dist/public!' || (echo '❌ ERROR: Frontend copy failed!' && exit 1)"
]

[start]
cmd = "cd backend && node dist/index.js"
