# Nixpacks Monorepo Configuration
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npm run build",
  "cd frontend && npm run build",
  "mkdir -p backend/dist/public",
  "cp -r frontend/dist/* backend/dist/public/ || echo 'Copy failed, trying alternative...'",
  "ls -la frontend/dist || echo 'Frontend dist not found'",
  "ls -la backend/dist/public || echo 'Public dir check'"
]

[start]
cmd = "cd /app/backend && chmod +x start.sh && ./start.sh"
