[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npx prisma generate", "cd backend && npm run build"]

[start]
cmd = "cd backend && npx prisma db push --accept-data-loss && npx prisma db seed && node dist/index.js"
