[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npx prisma generate", "cd backend && npm run build"]

[phases.deploy]
cmds = ["cd backend && npx prisma db push --accept-data-loss --skip-generate", "cd backend && npx prisma db seed"]

[start]
cmd = "cd backend && node dist/index.js"
