[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npx prisma generate && npm run build"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
