# Railway Monorepo Configuration
# Builds both backend and frontend, serves frontend from backend

[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npx prisma generate && npm run build && cd ../frontend && npm install && npm run build && cd .."
watchPatterns = ["backend/**", "frontend/**"]

[deploy]
startCommand = "cd backend && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
