# Railway Monorepo Configuration
# This builds both backend and frontend in one service

[build]
builder = "NIXPACKS"
buildCommand = """
  echo '=== Building Backend ===' && \
  cd backend && \
  npm install && \
  npx prisma generate && \
  npm run build && \
  cd .. && \
  echo '=== Building Frontend ===' && \
  cd frontend && \
  npm install && \
  npm run build && \
  cd ..
"""

[deploy]
startCommand = """
  cd backend && \
  npx serve ../frontend/dist -l 8080 & \
  node dist/index.js
"""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
